default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: konexzero_development

test:
  <<: *default
  database: konexzero_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
